
-- 创建schema
DROP SCHEMA IF EXISTS "TEST_SCAFFOLD" CASCADE;
CREATE SCHEMA "TEST_SCAFFOLD";
SET SCHEMA "TEST_SCAFFOLD";

-- 创建表结构
CREATE TABLE "T_DEVICE_NODE"
(
    "ID" BIGINT NOT NULL,
    "UPPER_ID" BIGINT NULL,
    "NODE_NAME" VARCHAR(50) NULL,
    "NODE_TYPE" CHAR(1) NULL,
    "CREATE_USER" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_USER" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "LEVEL" INT NULL,
    CLUSTER PRIMARY KEY("ID") ENABLE
);
COMMENT ON TABLE  "T_DEVICE_NODE" IS '设备节点';
COMMENT ON COLUMN "T_DEVICE_NODE"."ID" IS 'ID';
COMMENT ON COLUMN "T_DEVICE_NODE"."UPPER_ID" IS '上级ID';
COMMENT ON COLUMN "T_DEVICE_NODE"."NODE_NAME" IS '节点名称';
COMMENT ON COLUMN "T_DEVICE_NODE"."NODE_TYPE" IS '节点类型：0：地域节点，1：机房节点';
COMMENT ON COLUMN "T_DEVICE_NODE"."CREATE_USER" IS '创建者';
COMMENT ON COLUMN "T_DEVICE_NODE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_DEVICE_NODE"."UPDATE_USER" IS '更新者';
COMMENT ON COLUMN "T_DEVICE_NODE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_DEVICE_NODE"."LEVEL" IS '节点层级';

CREATE TABLE "T_DEVICE"
(
    "ID" BIGINT NOT NULL,
    "DEVICE_IP" VARCHAR(50) NULL,
    "DEVICE_SSH_USR" VARCHAR(50) NULL,
    "DEVICE_SSH_PWD" VARCHAR(200) NULL,
    "REMARK" VARCHAR(500) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "ENABLE_STATUS" CHAR(1) DEFAULT 0 NULL,
    "CONN_STATUS" VARCHAR(10) NULL,
    "CREATE_USER" VARCHAR(50) NULL,
    "UPDATE_USER" VARCHAR(50) NULL,
    "NODE_ID" BIGINT NULL,
    "PORT" INT NULL,
    "SCRIPT_VERSION" VARCHAR(50) NULL,
    "ARCH_TYPE" VARCHAR(1) NULL,
    "CPU_CORE" INT NULL,
    "MEM_TOTAL" VARCHAR(50) NULL,
    "DISK_TOTAL" VARCHAR(50) NULL,
    "OS_NAME" VARCHAR(50),
    "OS_VERSION" VARCHAR(200),
    "CPU_DESC" VARCHAR(50)
);
ALTER TABLE "T_DEVICE" ADD CONSTRAINT  PRIMARY KEY("ID") ;
COMMENT ON TABLE  "T_DEVICE" IS '设备表';
COMMENT ON COLUMN "T_DEVICE"."ID" IS '唯一标识';
COMMENT ON COLUMN "T_DEVICE"."DEVICE_IP" IS '设备IP';
COMMENT ON COLUMN "T_DEVICE"."DEVICE_SSH_USR" IS 'SSH登录名';
COMMENT ON COLUMN "T_DEVICE"."DEVICE_SSH_PWD" IS 'SSH登录密码';
COMMENT ON COLUMN "T_DEVICE"."REMARK" IS '说明';
COMMENT ON COLUMN "T_DEVICE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_DEVICE"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "T_DEVICE"."ENABLE_STATUS" IS '启用状态';
COMMENT ON COLUMN "T_DEVICE"."CONN_STATUS" IS '连接状态';
COMMENT ON COLUMN "T_DEVICE"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "T_DEVICE"."UPDATE_USER" IS '更新用户';
COMMENT ON COLUMN "T_DEVICE"."NODE_ID" IS '设备机房ID';
COMMENT ON COLUMN "T_DEVICE"."PORT" IS '设备端口';
COMMENT ON COLUMN "T_DEVICE"."SCRIPT_VERSION" IS '脚本版本';
COMMENT ON COLUMN "T_DEVICE"."ARCH_TYPE" IS '设备架构类型';
COMMENT ON COLUMN "T_DEVICE"."CPU_CORE" IS 'CPU核数';
COMMENT ON COLUMN "T_DEVICE"."MEM_TOTAL" IS '内存总量';
COMMENT ON COLUMN "T_DEVICE"."DISK_TOTAL" IS '磁盘总量';
COMMENT ON COLUMN "T_DEVICE"."OS_NAME" IS '操作系统名称';
COMMENT ON COLUMN "T_DEVICE"."OS_VERSION" IS '操作系统版本号';
COMMENT ON COLUMN "T_DEVICE"."CPU_DESC" IS 'CPU描述';

--告警消息表
CREATE TABLE "T_ALARM_MESSAGE"
(
	"ID" BIGINT NOT NULL,
	"SEND_METHOD" CHAR(1),
	"HTTP_URL" VARCHAR(500),
	"HTTP_SIGN" VARCHAR(500),
	"HTTPS_PROXY" VARCHAR(200),
	"TO_USER" VARCHAR(500),
	"SERVICE_CD" VARCHAR(50),
	"CLIENT_CD" VARCHAR(50),
	"SMS_TYPE" VARCHAR(50),
	"TO_PHONE" VARCHAR(500),
	"IS_USE" CHAR(1),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "T_ALARM_MESSAGE" IS '告警消息表';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."ID" IS '主键';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."SEND_METHOD" IS '通知行为，0:邮箱，1:飞书，2:钉钉，3:企业微信，4:短信通知，5:公众号';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."HTTP_URL" IS '通知地址';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."HTTP_SIGN" IS '机器人签名';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."HTTPS_PROXY" IS 'HTTPS代理地址';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."TO_USER" IS '消息发送对象';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."SERVICE_CD" IS '服务编码';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."CLIENT_CD" IS '请求方系统号';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."SMS_TYPE" IS '短信类型代码';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."TO_PHONE" IS '发送对象手机号';
COMMENT ON COLUMN "T_ALARM_MESSAGE"."IS_USE" IS '是否使用：0:未使用，1:使用';

CREATE TABLE "SYS_USER_ROLE"
(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL
);
ALTER TABLE "SYS_USER_ROLE" ADD CONSTRAINT  PRIMARY KEY("USER_ID","ROLE_ID") ;
COMMENT ON TABLE  "SYS_USER_ROLE" IS '用户和角色关联表';
COMMENT ON COLUMN "SYS_USER_ROLE"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "SYS_USER_ROLE"."ROLE_ID" IS '角色ID';

CREATE TABLE "SYS_USER"
(
    "USER_ID" BIGINT NOT NULL,
    "DEPT_ID" BIGINT NULL,
    "USER_NAME" VARCHAR(60) NULL,
    "NICK_NAME" VARCHAR(60) NULL,
    "EMAIL" VARCHAR(50) NULL,
    "PHONE_NUMBER" VARCHAR(11) NULL,
    "SEX" CHAR(1) DEFAULT 0 NULL,
    "AVATAR" TEXT NULL,
    "PASSWORD" VARCHAR(100) NULL,
    "STATUS" CHAR(1) DEFAULT 0 NULL,
    "DEL_FLAG" CHAR(1) DEFAULT 0 NULL,
    "LOGIN_IP" VARCHAR(128) NULL,
    "LOGIN_DATE" TIMESTAMP(6) NULL,
    "CREATE_BY" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_BY" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "REMARK" VARCHAR(500) NULL,
    "DOMAIN_ID" BIGINT DEFAULT 0 NULL,
    "OBJECT_GUID" VARCHAR(50) NULL,
    "LANGUAGE" VARCHAR(32) NULL
);
ALTER TABLE "SYS_USER" ADD CONSTRAINT  PRIMARY KEY("USER_ID") ;
COMMENT ON TABLE  "SYS_USER" IS '用户信息表';
COMMENT ON COLUMN "SYS_USER"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "SYS_USER"."DEPT_ID" IS '部门ID';
COMMENT ON COLUMN "SYS_USER"."USER_NAME" IS '用户账号';
COMMENT ON COLUMN "SYS_USER"."NICK_NAME" IS '用户昵称';
COMMENT ON COLUMN "SYS_USER"."EMAIL" IS '用户邮箱';
COMMENT ON COLUMN "SYS_USER"."PHONE_NUMBER" IS '手机号码';
COMMENT ON COLUMN "SYS_USER"."SEX" IS '用户性别（0男 1女 2未知）';
COMMENT ON COLUMN "SYS_USER"."AVATAR" IS '头像地址';
COMMENT ON COLUMN "SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SYS_USER"."STATUS" IS '帐号状态（0正常 1停用）';
COMMENT ON COLUMN "SYS_USER"."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "SYS_USER"."LOGIN_IP" IS '最后登录IP';
COMMENT ON COLUMN "SYS_USER"."LOGIN_DATE" IS '最后登录时间';
COMMENT ON COLUMN "SYS_USER"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_USER"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_USER"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_USER"."DOMAIN_ID" IS '导入域id（0表示手动添加）';
COMMENT ON COLUMN "SYS_USER"."OBJECT_GUID" IS 'ad域内用户唯一标识';
COMMENT ON COLUMN "SYS_USER"."LANGUAGE" IS '语言配置(不设置默认为中文)';

CREATE TABLE "SYS_ROLE_MENU"
(
    "ROLE_ID" BIGINT NOT NULL,
    "MENU_ID" BIGINT NOT NULL
);
ALTER TABLE "SYS_ROLE_MENU" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID","MENU_ID") ;
COMMENT ON TABLE  "SYS_ROLE_MENU" IS '角色和菜单关联表';
COMMENT ON COLUMN "SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';

CREATE TABLE "SYS_ROLE"
(
    "ROLE_ID" BIGINT NOT NULL,
    "ROLE_NAME" VARCHAR(60) NULL,
    "ROLE_SORT" INT NULL,
    "DATA_SCOPE" CHAR(1) DEFAULT 1 NULL,
    "STATUS" CHAR(1) DEFAULT 0 NULL,
    "DEL_FLAG" CHAR(1) DEFAULT 0 NULL,
    "CREATE_BY" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_BY" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "REMARK" VARCHAR(500) NULL,
    "ROLE_NAME_EN" VARCHAR(200)
);
ALTER TABLE "SYS_ROLE" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID") ;
COMMENT ON TABLE  "SYS_ROLE" IS '角色信息表';
COMMENT ON COLUMN "SYS_ROLE"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYS_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "SYS_ROLE"."ROLE_NAME_EN" IS '角色名称（英文）';
COMMENT ON COLUMN "SYS_ROLE"."ROLE_SORT" IS '显示顺序';
COMMENT ON COLUMN "SYS_ROLE"."DATA_SCOPE" IS '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
COMMENT ON COLUMN "SYS_ROLE"."STATUS" IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN "SYS_ROLE"."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "SYS_ROLE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_ROLE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_ROLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_ROLE"."REMARK" IS '备注';

CREATE TABLE "SYS_OPER_LOG"
(
    "OPER_ID" BIGINT IDENTITY(1,1) NOT NULL,
    "TITLE" VARCHAR(50) NULL,
    "BUSINESS_TYPE" INT DEFAULT 0 NULL,
    "METHOD" VARCHAR(100) NULL,
    "REQUEST_METHOD" VARCHAR(10) NULL,
    "OPERATOR_TYPE" INT DEFAULT 0 NULL,
    "OPER_NAME" VARCHAR(50) NULL,
    "DEPT_NAME" VARCHAR(50) NULL,
    "OPER_URL" VARCHAR(255) NULL,
    "OPER_IP" VARCHAR(128) NULL,
    "OPER_PARAM" TEXT NULL,
    "JSON_RESULT" VARCHAR(4000) NULL,
    "STATUS" INT DEFAULT 0 NULL,
    "ERROR_MSG" VARCHAR(2000) NULL,
    "OPER_TIME" TIMESTAMP(6) NULL
);
ALTER TABLE "SYS_OPER_LOG" ADD CONSTRAINT  PRIMARY KEY("OPER_ID") ;
COMMENT ON TABLE  "SYS_OPER_LOG" IS '操作日志记录';
COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_ID" IS '日志主键';
COMMENT ON COLUMN "SYS_OPER_LOG"."TITLE" IS '模块标题';
COMMENT ON COLUMN "SYS_OPER_LOG"."BUSINESS_TYPE" IS '业务类型（0其它 1新增 2修改 3删除）';
COMMENT ON COLUMN "SYS_OPER_LOG"."METHOD" IS '方法名称';
COMMENT ON COLUMN "SYS_OPER_LOG"."REQUEST_METHOD" IS '请求方式';
COMMENT ON COLUMN "SYS_OPER_LOG"."OPERATOR_TYPE" IS '操作类别（0其它 1后台用户 2手机端用户）';
COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_NAME" IS '操作人员';
COMMENT ON COLUMN "SYS_OPER_LOG"."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_URL" IS '请求URL';
COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_IP" IS '主机地址';
COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_PARAM" IS '请求参数';
COMMENT ON COLUMN "SYS_OPER_LOG"."JSON_RESULT" IS '返回参数';
COMMENT ON COLUMN "SYS_OPER_LOG"."STATUS" IS '操作状态（0正常 1异常）';
COMMENT ON COLUMN "SYS_OPER_LOG"."ERROR_MSG" IS '错误消息';
COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_TIME" IS '操作时间';

CREATE TABLE "SYS_MENU"
(
    "MENU_ID" BIGINT IDENTITY(1,1) NOT NULL,
    "MENU_NAME" VARCHAR(50) NULL,
    "PARENT_ID" BIGINT DEFAULT 0 NULL,
    "ORDER_NUM" INT DEFAULT 0 NULL,
    "PATH" VARCHAR(200) NULL,
    "COMPONENT" VARCHAR(255) NULL,
    "QUERY" VARCHAR(255) NULL,
    "IS_FRAME" INT DEFAULT 1 NULL,
    "IS_CACHE" INT DEFAULT 0 NULL,
    "MENU_TYPE" CHAR(1) NULL,
    "VISIBLE" CHAR(1) DEFAULT 0 NULL,
    "STATUS" CHAR(1) DEFAULT 0 NULL,
    "PERMS" VARCHAR(100) NULL,
    "ICON" VARCHAR(100) DEFAULT '#' NULL,
    "CREATE_BY" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_BY" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "REMARK" VARCHAR(500) NULL
);
ALTER TABLE "SYS_MENU" ADD CONSTRAINT  PRIMARY KEY("MENU_ID") ;
COMMENT ON TABLE  "SYS_MENU" IS '菜单权限表';
COMMENT ON COLUMN "SYS_MENU"."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN "SYS_MENU"."MENU_NAME" IS '菜单名称';
COMMENT ON COLUMN "SYS_MENU"."PARENT_ID" IS '父菜单ID';
COMMENT ON COLUMN "SYS_MENU"."ORDER_NUM" IS '显示顺序';
COMMENT ON COLUMN "SYS_MENU"."PATH" IS '路由地址';
COMMENT ON COLUMN "SYS_MENU"."COMPONENT" IS '组件路径';
COMMENT ON COLUMN "SYS_MENU"."QUERY" IS '路由参数';
COMMENT ON COLUMN "SYS_MENU"."IS_FRAME" IS '是否为外链（0是 1否）';
COMMENT ON COLUMN "SYS_MENU"."IS_CACHE" IS '是否缓存（0缓存 1不缓存）';
COMMENT ON COLUMN "SYS_MENU"."MENU_TYPE" IS '菜单类型（M目录 C菜单 F按钮）';
COMMENT ON COLUMN "SYS_MENU"."VISIBLE" IS '菜单状态（0显示 1隐藏）';
COMMENT ON COLUMN "SYS_MENU"."STATUS" IS '菜单状态（0正常 1停用）';
COMMENT ON COLUMN "SYS_MENU"."PERMS" IS '权限标识';
COMMENT ON COLUMN "SYS_MENU"."ICON" IS '菜单图标';
COMMENT ON COLUMN "SYS_MENU"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_MENU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_MENU"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_MENU"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_MENU"."REMARK" IS '备注';

CREATE TABLE "SYS_LOGININFOR"
(
    "INFO_ID" BIGINT IDENTITY(1,1) NOT NULL,
    "USER_NAME" VARCHAR(50) NULL,
    "IPADDR" VARCHAR(128) NULL,
    "STATUS" CHAR(1) NULL,
    "MSG" VARCHAR(255) NULL,
    "ACCESS_TIME" TIMESTAMP(6) NULL,
    "LOGIN_LOCATION" VARCHAR(50) NULL,
    "BROWSER" VARCHAR(50) NULL,
    "OS" VARCHAR(50) NULL
);
ALTER TABLE "SYS_LOGININFOR" ADD CONSTRAINT  PRIMARY KEY("INFO_ID") ;
COMMENT ON TABLE  "SYS_LOGININFOR" IS '系统访问记录';
COMMENT ON COLUMN "SYS_LOGININFOR"."INFO_ID" IS '访问ID';
COMMENT ON COLUMN "SYS_LOGININFOR"."USER_NAME" IS '用户账号';
COMMENT ON COLUMN "SYS_LOGININFOR"."IPADDR" IS '登录IP地址';
COMMENT ON COLUMN "SYS_LOGININFOR"."STATUS" IS '登录状态（0成功 1失败）';
COMMENT ON COLUMN "SYS_LOGININFOR"."MSG" IS '提示信息';
COMMENT ON COLUMN "SYS_LOGININFOR"."ACCESS_TIME" IS '访问时间';

CREATE TABLE "SYS_JOB_LOG"
(
    "JOB_LOG_ID" BIGINT NOT NULL,
    "JOB_MESSAGE" VARCHAR(500) NULL,
    "STATUS" CHAR(1) DEFAULT 0 NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "MONITOR_VALUES" FLOAT(53) DEFAULT 0 NULL,
    "ALARM_CONDITION" VARCHAR(2) NULL,
    "ALARM_VALUES" FLOAT(53) NULL,
    "OBJECT_ID" BIGINT NULL,
    "OBJECT_ITEM" VARCHAR(100),
    "OBJECT_NAME" VARCHAR(500)
);
ALTER TABLE "SYS_JOB_LOG" ADD CONSTRAINT  PRIMARY KEY("JOB_LOG_ID") ;
COMMENT ON TABLE  "SYS_JOB_LOG" IS '定时任务调度日志表';
COMMENT ON COLUMN "SYS_JOB_LOG"."JOB_LOG_ID" IS '任务日志ID';
COMMENT ON COLUMN "SYS_JOB_LOG"."JOB_MESSAGE" IS '日志信息';
COMMENT ON COLUMN "SYS_JOB_LOG"."STATUS" IS '执行状态（0正常 1失败）';
COMMENT ON COLUMN "SYS_JOB_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_JOB_LOG"."MONITOR_VALUES" IS '监控实际值(百分比、KB)';
COMMENT ON COLUMN "SYS_JOB_LOG"."ALARM_CONDITION" IS '告警项（3 设备 内存使用率， 4 设备 CPU使用率， 5 设备 磁盘使用率）';
COMMENT ON COLUMN "SYS_JOB_LOG"."ALARM_VALUES" IS '告警阈值';
COMMENT ON COLUMN "SYS_JOB_LOG"."OBJECT_ID" IS '对象id（设备或节点）';
COMMENT ON COLUMN "SYS_JOB_LOG"."OBJECT_ITEM" IS '对象细分指标';
COMMENT ON COLUMN "SYS_JOB_LOG"."OBJECT_NAME" IS '对象名称';

CREATE TABLE "SYS_ID"
(
    "SYS_ID" BIGINT NULL
);
COMMENT ON TABLE  "SYS_ID" IS '系统唯一标识';
COMMENT ON COLUMN "SYS_ID"."SYS_ID" IS '系统唯一标识';

CREATE TABLE "SYS_DOMAIN_MAPPING"
(
    "ID" BIGINT NOT NULL,
    "DOMAIN_ID" BIGINT NULL,
    "MANAGER_USER_PROP" VARCHAR(50) NULL,
    "DOMAIN_USER_PROP" VARCHAR(50) NULL,
    CLUSTER PRIMARY KEY("ID") ENABLE
);
COMMENT ON TABLE  "SYS_DOMAIN_MAPPING" IS '域用户属性映射表';
COMMENT ON COLUMN "SYS_DOMAIN_MAPPING"."ID" IS '主键id';
COMMENT ON COLUMN "SYS_DOMAIN_MAPPING"."DOMAIN_ID" IS '域id';
COMMENT ON COLUMN "SYS_DOMAIN_MAPPING"."MANAGER_USER_PROP" IS 'manager用户属性';
COMMENT ON COLUMN "SYS_DOMAIN_MAPPING"."DOMAIN_USER_PROP" IS 'ad域用户属性';

CREATE TABLE "SYS_DOMAIN"
(
    "ID" BIGINT NOT NULL,
    "SERVER_HOST" VARCHAR(50) NULL,
    "SERVER_PORT" INT NULL,
    "SSL_ENABLE" CHAR(1) NULL,
    "BASE_DN" VARCHAR(500) NULL,
    "DEPT_FILTER" VARCHAR(500) NULL,
    "USER_FILTER" VARCHAR(500) NULL,
    "ADMIN_ACCOUNT" VARCHAR(50) NULL,
    "ADMIN_PASS" VARCHAR(50) NULL,
    "CREATE_USER" VARCHAR(50) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_USER" VARCHAR(50) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "SYNC_ENABLE" CHAR(1) DEFAULT 0 NULL,
    "SYNC_CRON" VARCHAR(50) NULL,
    CLUSTER PRIMARY KEY("ID") ENABLE
);
COMMENT ON TABLE  "SYS_DOMAIN" IS '域信息表';
COMMENT ON COLUMN "SYS_DOMAIN"."ID" IS '主键ID';
COMMENT ON COLUMN "SYS_DOMAIN"."SERVER_HOST" IS '服务器地址';
COMMENT ON COLUMN "SYS_DOMAIN"."SERVER_PORT" IS '服务端口';
COMMENT ON COLUMN "SYS_DOMAIN"."SSL_ENABLE" IS '是否开启SSL(0 关闭 1 开启)';
COMMENT ON COLUMN "SYS_DOMAIN"."BASE_DN" IS '基准目录';
COMMENT ON COLUMN "SYS_DOMAIN"."DEPT_FILTER" IS '部门过滤';
COMMENT ON COLUMN "SYS_DOMAIN"."USER_FILTER" IS '用户过滤';
COMMENT ON COLUMN "SYS_DOMAIN"."ADMIN_ACCOUNT" IS '管理员账号';
COMMENT ON COLUMN "SYS_DOMAIN"."ADMIN_PASS" IS '管理员密码';
COMMENT ON COLUMN "SYS_DOMAIN"."CREATE_USER" IS '创建人';
COMMENT ON COLUMN "SYS_DOMAIN"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_DOMAIN"."UPDATE_USER" IS '修改人';
COMMENT ON COLUMN "SYS_DOMAIN"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "SYS_DOMAIN"."SYNC_ENABLE" IS '是否开启定时同步（0 关闭 1开启）';
COMMENT ON COLUMN "SYS_DOMAIN"."SYNC_CRON" IS '定时同步cron表达式';

CREATE TABLE "SYS_DICT_TYPE"
(
    "DICT_ID" BIGINT IDENTITY(1,1) NOT NULL,
    "DICT_NAME" VARCHAR(100) NULL,
    "DICT_TYPE" VARCHAR(100) NULL,
    "STATUS" CHAR(1) DEFAULT 0 NULL,
    "CREATE_BY" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_BY" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "REMARK" VARCHAR(500) NULL
);
ALTER TABLE "SYS_DICT_TYPE" ADD CONSTRAINT  PRIMARY KEY("DICT_ID") ;
COMMENT ON TABLE  "SYS_DICT_TYPE" IS '字典类型表';
COMMENT ON COLUMN "SYS_DICT_TYPE"."DICT_ID" IS '字典主键';
COMMENT ON COLUMN "SYS_DICT_TYPE"."DICT_NAME" IS '字典名称';
COMMENT ON COLUMN "SYS_DICT_TYPE"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "SYS_DICT_TYPE"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "SYS_DICT_TYPE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_DICT_TYPE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_DICT_TYPE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_DICT_TYPE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_DICT_TYPE"."REMARK" IS '备注';

CREATE TABLE "SYS_DICT_DATA"
(
    "DICT_CODE" BIGINT IDENTITY(1,1) NOT NULL,
    "DICT_SORT" INT DEFAULT 0 NULL,
    "DICT_LABEL" VARCHAR(100) NULL,
    "DICT_VALUE" VARCHAR(100) NULL,
    "DICT_TYPE" VARCHAR(100) NULL,
    "CSS_CLASS" VARCHAR(100) NULL,
    "LIST_CLASS" VARCHAR(100) NULL,
    "IS_DEFAULT" CHAR(1) DEFAULT 'N' NULL,
    "STATUS" CHAR(1) DEFAULT 0 NULL,
    "CREATE_BY" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_BY" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "REMARK" VARCHAR(500) NULL
);
ALTER TABLE "SYS_DICT_DATA" ADD CONSTRAINT  PRIMARY KEY("DICT_CODE") ;
COMMENT ON TABLE  "SYS_DICT_DATA" IS '字典数据表';
COMMENT ON COLUMN "SYS_DICT_DATA"."DICT_CODE" IS '字典编码';
COMMENT ON COLUMN "SYS_DICT_DATA"."DICT_SORT" IS '字典排序';
COMMENT ON COLUMN "SYS_DICT_DATA"."DICT_LABEL" IS '字典标签';
COMMENT ON COLUMN "SYS_DICT_DATA"."DICT_VALUE" IS '字典键值';
COMMENT ON COLUMN "SYS_DICT_DATA"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "SYS_DICT_DATA"."CSS_CLASS" IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN "SYS_DICT_DATA"."LIST_CLASS" IS '表格回显样式';
COMMENT ON COLUMN "SYS_DICT_DATA"."IS_DEFAULT" IS '是否默认（Y是 N否）';
COMMENT ON COLUMN "SYS_DICT_DATA"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "SYS_DICT_DATA"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_DICT_DATA"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_DICT_DATA"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_DICT_DATA"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_DICT_DATA"."REMARK" IS '备注';

CREATE TABLE "SYS_DEPT"
(
    "DEPT_ID" BIGINT NOT NULL,
    "PARENT_ID" BIGINT DEFAULT 0 NULL,
    "ANCESTORS" VARCHAR(50) NULL,
    "DEPT_NAME" VARCHAR(60) NULL,
    "ORDER_NUM" INT DEFAULT 0 NULL,
    "LEADER" VARCHAR(40) NULL,
    "PHONE" VARCHAR(11) NULL,
    "EMAIL" VARCHAR(50) NULL,
    "STATUS" CHAR(1) DEFAULT 0 NULL,
    "DEL_FLAG" CHAR(1) DEFAULT 0 NULL,
    "CREATE_BY" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_BY" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "DEPT_NAME_EN" VARCHAR(200)
);
ALTER TABLE "SYS_DEPT" ADD CONSTRAINT  PRIMARY KEY("DEPT_ID") ;
COMMENT ON TABLE  "SYS_DEPT" IS '部门表';
COMMENT ON COLUMN "SYS_DEPT"."DEPT_ID" IS '部门id';
COMMENT ON COLUMN "SYS_DEPT"."PARENT_ID" IS '父部门id';
COMMENT ON COLUMN "SYS_DEPT"."ANCESTORS" IS '祖级列表';
COMMENT ON COLUMN "SYS_DEPT"."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "SYS_DEPT"."DEPT_NAME_EN" IS '部门名称（英文）';
COMMENT ON COLUMN "SYS_DEPT"."ORDER_NUM" IS '显示顺序';
COMMENT ON COLUMN "SYS_DEPT"."LEADER" IS '负责人';
COMMENT ON COLUMN "SYS_DEPT"."PHONE" IS '联系电话';
COMMENT ON COLUMN "SYS_DEPT"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "SYS_DEPT"."STATUS" IS '部门状态（0正常 1停用）';
COMMENT ON COLUMN "SYS_DEPT"."DEL_FLAG" IS '删除标志（0代表存在 2代表删除）';
COMMENT ON COLUMN "SYS_DEPT"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_DEPT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_DEPT"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_DEPT"."UPDATE_TIME" IS '更新时间';

CREATE TABLE "SYS_CONFIG"
(
    "CONFIG_ID" INT IDENTITY(1,1) NOT NULL,
    "CONFIG_NAME" VARCHAR(100) NULL,
    "CONFIG_KEY" VARCHAR(100) NULL,
    "CONFIG_VALUE" VARCHAR(500) NULL,
    "CONFIG_TYPE" CHAR(1) DEFAULT 'N' NULL,
    "CREATE_BY" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_BY" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "REMARK" VARCHAR(500) NULL
);
ALTER TABLE "SYS_CONFIG" ADD CONSTRAINT  PRIMARY KEY("CONFIG_ID") ;
COMMENT ON TABLE  "SYS_CONFIG" IS '参数配置表';
COMMENT ON COLUMN "SYS_CONFIG"."CONFIG_ID" IS '参数主键';
COMMENT ON COLUMN "SYS_CONFIG"."CONFIG_NAME" IS '参数名称';
COMMENT ON COLUMN "SYS_CONFIG"."CONFIG_KEY" IS '参数键名';
COMMENT ON COLUMN "SYS_CONFIG"."CONFIG_VALUE" IS '参数键值';
COMMENT ON COLUMN "SYS_CONFIG"."CONFIG_TYPE" IS '系统内置（Y是 N否）';
COMMENT ON COLUMN "SYS_CONFIG"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SYS_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_CONFIG"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SYS_CONFIG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_CONFIG"."REMARK" IS '备注';

CREATE TABLE "SYS_JOB"
(
    "JOB_ID" BIGINT NOT NULL,
    "JOB_NAME" VARCHAR(64) NULL,
    "JOB_GROUP" VARCHAR(64) NULL,
    "JOB_PARAM" VARCHAR(500) NULL,
    "BEAN_TARGET" VARCHAR(100) NULL,
    "BEAN_METHOD_TARGET" VARCHAR(100) NULL,
    "CRON_EXPRESSION" VARCHAR(255) NULL,
    "CONCURRENT" CHAR(1) NULL,
    "MISFIRE_POLICY" CHAR(1) NULL,
    "CREATE_USER" VARCHAR(64) NULL,
    "CREATE_TIME" TIMESTAMP(6) NULL,
    "UPDATE_USER" VARCHAR(64) NULL,
    "UPDATE_TIME" TIMESTAMP(6) NULL,
    "REMARK" VARCHAR(500) NULL
);
ALTER TABLE "SYS_JOB" ADD CONSTRAINT  PRIMARY KEY("JOB_ID") ;
COMMENT ON TABLE  "SYS_JOB" IS '定时任务调度表';
COMMENT ON COLUMN "SYS_JOB"."JOB_ID" IS '任务ID';
COMMENT ON COLUMN "SYS_JOB"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "SYS_JOB"."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "SYS_JOB"."JOB_PARAM" IS '任务参数';
COMMENT ON COLUMN "SYS_JOB"."BEAN_TARGET" IS '调用目标类';
COMMENT ON COLUMN "SYS_JOB"."BEAN_METHOD_TARGET" IS '调用目标方法';
COMMENT ON COLUMN "SYS_JOB"."CRON_EXPRESSION" IS 'cron执行表达式';
COMMENT ON COLUMN "SYS_JOB"."CONCURRENT" IS '是否并发 0允许 1不允许';
COMMENT ON COLUMN "SYS_JOB"."MISFIRE_POLICY" IS '计划策略';
COMMENT ON COLUMN "SYS_JOB"."CREATE_USER" IS '创建者';
COMMENT ON COLUMN "SYS_JOB"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_JOB"."UPDATE_USER" IS '更新者';
COMMENT ON COLUMN "SYS_JOB"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SYS_JOB"."REMARK" IS '备注';

CREATE TABLE "SYS_QUARTZ_JOB_LOG"
(
    "LOG_ID" BIGINT NOT NULL,
    "JOB_NAME" VARCHAR(64) NULL,
    "TRIG_NAME" VARCHAR(64) NULL,
    "START_TIME" TIMESTAMP(6) NULL,
    "END_TIME" TIMESTAMP(6) NULL,
    "CONTENT" VARCHAR(500) NULL,
    "STATUS" CHAR(1) NULL,
    "DURATION" BIGINT NULL
);
ALTER TABLE "SYS_QUARTZ_JOB_LOG" ADD CONSTRAINT  PRIMARY KEY("LOG_ID") ;
COMMENT ON TABLE  "SYS_QUARTZ_JOB_LOG" IS '定时任务日志表';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."LOG_ID" IS '主键';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."TRIG_NAME" IS '触发器名称';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."CONTENT" IS '执行情况';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."STATUS" IS '状态';
COMMENT ON COLUMN "SYS_QUARTZ_JOB_LOG"."DURATION" IS '持续时间';

--数据采集频率配置表
CREATE TABLE "SYS_SOFT_AGENT_CONFIG"
(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR2(400),
    "CODE" VARCHAR2(100),
    "CRON_EXPRESSION" VARCHAR2(500),
    "GROUPS" VARCHAR2(20),
    "REMARK" VARCHAR2(1000),
    NOT CLUSTER PRIMARY KEY("ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE "SYS_SOFT_AGENT_CONFIG" IS '数据采集频率配置表';
COMMENT ON COLUMN "SYS_SOFT_AGENT_CONFIG"."ID" IS '主键';
COMMENT ON COLUMN "SYS_SOFT_AGENT_CONFIG"."NAME" IS '参数名称';
COMMENT ON COLUMN "SYS_SOFT_AGENT_CONFIG"."CODE" IS '参数编码';
COMMENT ON COLUMN "SYS_SOFT_AGENT_CONFIG"."CRON_EXPRESSION" IS 'cron表达式';
COMMENT ON COLUMN "SYS_SOFT_AGENT_CONFIG"."GROUPS" IS '分组 device';
COMMENT ON COLUMN "SYS_SOFT_AGENT_CONFIG"."REMARK" IS '备注';

--告警项通知方式配置表
CREATE TABLE "T_ALERT_NOTICE_CONFIG"
(
    "ID" BIGINT NOT NULL,
    "OBJECT_ID" BIGINT NOT NULL,
    "ALERT_RULE_ID" BIGINT NOT NULL,
    "ALERT_CONFIG_ID" BIGINT NOT NULL,
    "ALARM_MESSAGE_ID" BIGINT NOT NULL,
    "RECIPIENT" VARCHAR2(500),
    NOT CLUSTER PRIMARY KEY("ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE "T_ALERT_NOTICE_CONFIG" IS '告警项通知方式配置表';
COMMENT ON COLUMN "T_ALERT_NOTICE_CONFIG"."ID" IS '主键';
COMMENT ON COLUMN "T_ALERT_NOTICE_CONFIG"."OBJECT_ID" IS '对象ID(设备或节点ID)';
COMMENT ON COLUMN "T_ALERT_NOTICE_CONFIG"."ALERT_RULE_ID" IS '告警规则ID';
COMMENT ON COLUMN "T_ALERT_NOTICE_CONFIG"."ALERT_CONFIG_ID" IS '告警配置ID';
COMMENT ON COLUMN "T_ALERT_NOTICE_CONFIG"."ALARM_MESSAGE_ID" IS '告警通知方式ID';
COMMENT ON COLUMN "T_ALERT_NOTICE_CONFIG"."RECIPIENT" IS '接受人(多个用逗号隔开)';

--告警规则配置表
CREATE TABLE "T_ALERT_CONFIG"
(
    "ID" BIGINT NOT NULL,
    "RULE_ID" BIGINT NOT NULL,
    "RULE_NAME" VARCHAR(300) NOT NULL,
    "RULE_GROUPS" VARCHAR(32) NOT NULL,
    "OBJECT_ID" BIGINT NOT NULL,
    "PARAMETERS" VARCHAR(4000),
    "STATUS" VARCHAR(10),
    "TABLE_NAME" VARCHAR(20),
    "PROCESSOR" VARCHAR(500),
    "MEMO" VARCHAR(1000),
    "RULE_CODE" VARCHAR2(100),
    "RULE_DESC" VARCHAR2(4000),
    "DB_NAME" VARCHAR(500),
    "RULE_TYPE" CHAR(1),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "T_ALERT_CONFIG" IS '告警规则配置表：针对不同的设备和实例告警规则不同';
COMMENT ON COLUMN "T_ALERT_CONFIG"."ID" IS '主键';
COMMENT ON COLUMN "T_ALERT_CONFIG"."MEMO" IS '备注';
COMMENT ON COLUMN "T_ALERT_CONFIG"."OBJECT_ID" IS '告警对象id';
COMMENT ON COLUMN "T_ALERT_CONFIG"."PARAMETERS" IS '参数JSON';
COMMENT ON COLUMN "T_ALERT_CONFIG"."PROCESSOR" IS '告警处理过程类';
COMMENT ON COLUMN "T_ALERT_CONFIG"."RULE_CODE" IS '规则编码';
COMMENT ON COLUMN "T_ALERT_CONFIG"."RULE_DESC" IS '规则描述';
COMMENT ON COLUMN "T_ALERT_CONFIG"."RULE_GROUPS" IS '分组';
COMMENT ON COLUMN "T_ALERT_CONFIG"."RULE_ID" IS '告警规则定义ID: 关联ALERT_RULE.ID';
COMMENT ON COLUMN "T_ALERT_CONFIG"."RULE_NAME" IS '告警名称';
COMMENT ON COLUMN "T_ALERT_CONFIG"."STATUS" IS '启用状态：yes\no';
COMMENT ON COLUMN "T_ALERT_CONFIG"."TABLE_NAME" IS '告警对象表';
COMMENT ON COLUMN "T_ALERT_CONFIG"."DB_NAME" IS '实例数据库名称';
COMMENT ON COLUMN "T_ALERT_CONFIG"."RULE_TYPE" IS '规则类型:0设备,1实例,2实例数据库';

--告警规则定义表
CREATE TABLE "T_ALERT_RULE"
(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(300),
    "MEMO" VARCHAR(1000),
    "PROCESSOR" VARCHAR(500),
    "PARAMETERS" VARCHAR(4000),
    "GROUPS" VARCHAR(200),
    "TABLE_NAME" VARCHAR(20),
    "CODE" VARCHAR2(100),
    "RULE_DESC" VARCHAR2(4000),
    "STATUS" VARCHAR(10),
    "RULE_TYPE" CHAR(1),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "T_ALERT_RULE" IS '告警规则定义表';
COMMENT ON COLUMN "T_ALERT_RULE"."CODE" IS '规则编码';
COMMENT ON COLUMN "T_ALERT_RULE"."GROUPS" IS '分组：资源利用告警，性能监控相关告警，软件版本相关告警';
COMMENT ON COLUMN "T_ALERT_RULE"."ID" IS '主键';
COMMENT ON COLUMN "T_ALERT_RULE"."MEMO" IS '备注';
COMMENT ON COLUMN "T_ALERT_RULE"."NAME" IS '告警名称';
COMMENT ON COLUMN "T_ALERT_RULE"."PARAMETERS" IS '告警参数JSON';
COMMENT ON COLUMN "T_ALERT_RULE"."PROCESSOR" IS '告警处理过程类';
COMMENT ON COLUMN "T_ALERT_RULE"."RULE_DESC" IS '规则描述';
COMMENT ON COLUMN "T_ALERT_RULE"."STATUS" IS '默认启用状态：yes\no';
COMMENT ON COLUMN "T_ALERT_RULE"."TABLE_NAME" IS '所属对象表';
COMMENT ON COLUMN "T_ALERT_RULE"."RULE_TYPE" IS '规则类型:0设备,1实例,2实例数据库';

--告警通知消息记录表
CREATE TABLE "T_ALERT_NOTICE_MESSAGE"
(
    "ID" BIGINT NOT NULL,
    "OBJECT_ID" BIGINT NOT NULL,
    "RECIPIENT" VARCHAR2(4000),
    "TITLE" VARCHAR2(100),
    "CONTENT" TEXT,
    "ALERT_LEVEL" VARCHAR2(10),
    "NOTICE_METHOD" CHAR(1),
    "NOTICE_TIME" TIMESTAMP(6),
    "IS_SUCCESS" CHAR(1),
    "ERROR_MESSAGE" VARCHAR2(2000),
    "TITLE_EN" VARCHAR2(1000),
    "CONTENT_EN" TEXT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "T_ALERT_NOTICE_MESSAGE" IS '告警通知消息记录表';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."ALERT_LEVEL" IS '告警级别，fatal:严重、warn：警告';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."CONTENT" IS '消息内容';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."CONTENT_EN" IS '消息内容英文';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."ERROR_MESSAGE" IS '通知失败返回错误内容';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."ID" IS '主键';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."IS_SUCCESS" IS '是否成功 0失败 1成功';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."NOTICE_METHOD" IS '通知方式 关联ALERT_NOTICE_METHOD表KEY';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."NOTICE_TIME" IS '通知时间';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."OBJECT_ID" IS '告警对象ID';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."RECIPIENT" IS '接受人';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."TITLE" IS '消息标题';
COMMENT ON COLUMN "T_ALERT_NOTICE_MESSAGE"."TITLE_EN" IS '消息标题英文';

--系统消息、监控告警表
CREATE TABLE "SYS_MESSAGE"
(
    "ID" BIGINT NOT NULL,
    "OBJECT_ID" VARCHAR(32),
    "RESOURCE_NAME" VARCHAR(200),
    "RULE_ID" BIGINT NOT NULL,
    "TITLE" VARCHAR(100),
    "CONTENT" VARCHAR(4000),
    "CREATE_TIME" TIMESTAMP(6),
    "MSG_LEVEL" VARCHAR(10),
    "MSG_KIND" VARCHAR(10),
    "TABLE_NAME" VARCHAR(50),
    "SEND_MAIL_STATUS" VARCHAR(50),
    "SEND_TIME" TIMESTAMP(6),
    "END_TIME" TIMESTAMP(6),
    "ACTIVE_STATE" VARCHAR(10),
    "TITLE_EN" VARCHAR(1000),
    "CONTENT_EN" VARCHAR(4000),
    "ALARM_CONDITION" VARCHAR(6),
    NOT CLUSTER PRIMARY KEY("ID"))
    PARTITION BY RANGE("CREATE_TIME")
INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION  "PART_20250101"  VALUES LESS THAN(DATETIME'2025-01-01 00:00:00') STORAGE(ON "MAIN", CLUSTERBTR)
) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_MESSAGE" IS '系统消息、监控告警表';
COMMENT ON COLUMN "SYS_MESSAGE"."ACTIVE_STATE" IS '有效状态：有效live,过期无效death,关闭失效killed';
COMMENT ON COLUMN "SYS_MESSAGE"."CONTENT" IS '消息内容';
COMMENT ON COLUMN "SYS_MESSAGE"."CONTENT_EN" IS '消息内容英文';
COMMENT ON COLUMN "SYS_MESSAGE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SYS_MESSAGE"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "SYS_MESSAGE"."ID" IS '主键ID';
COMMENT ON COLUMN "SYS_MESSAGE"."MSG_KIND" IS '类型：告警信息alert,其它消息other';
COMMENT ON COLUMN "SYS_MESSAGE"."MSG_LEVEL" IS '消息级别：正常normal,warning,fatal';
COMMENT ON COLUMN "SYS_MESSAGE"."OBJECT_ID" IS '资源ID';
COMMENT ON COLUMN "SYS_MESSAGE"."RESOURCE_NAME" IS '资源名称';
COMMENT ON COLUMN "SYS_MESSAGE"."RULE_ID" IS '规则ID：关联ALERT_RULE.ID';
COMMENT ON COLUMN "SYS_MESSAGE"."SEND_MAIL_STATUS" IS '发送邮件状态';
COMMENT ON COLUMN "SYS_MESSAGE"."SEND_TIME" IS '发送时间';
COMMENT ON COLUMN "SYS_MESSAGE"."TABLE_NAME" IS '设备对象表';
COMMENT ON COLUMN "SYS_MESSAGE"."TITLE" IS '消息标题';
COMMENT ON COLUMN "SYS_MESSAGE"."TITLE_EN" IS '消息标题英文';
COMMENT ON COLUMN "SYS_MESSAGE"."ALARM_CONDITION" IS '告警项';

CREATE TABLE "SYS_MESSAGE_TIP"
(
    "ID" VARCHAR(32) NOT NULL,
    "DATA_ID" VARCHAR(100),
    "TABLE_NAME" VARCHAR(100),
    "LANG" VARCHAR(50),
    "REMARK" CLOB,
    "CODE" VARCHAR(100),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE "SYS_MESSAGE_TIP" IS '系统信息语言标识表';
COMMENT ON COLUMN "SYS_MESSAGE_TIP"."ID" IS '主键';
COMMENT ON COLUMN "SYS_MESSAGE_TIP"."DATA_ID" IS '业务id';
COMMENT ON COLUMN "SYS_MESSAGE_TIP"."TABLE_NAME" IS '关联表';
COMMENT ON COLUMN "SYS_MESSAGE_TIP"."LANG" IS '语言标识';
COMMENT ON COLUMN "SYS_MESSAGE_TIP"."REMARK" IS '模版内容';
COMMENT ON COLUMN "SYS_MESSAGE_TIP"."CODE" IS 'code编码';
